name: Check Tennispro Stock

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run scripts
        run: |
          python check_cb26.py
          python check_tour_ace_rough.py
          python check_tour_ace_spin.py
          python check_slinger.py
          python check_cb14pro.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add stock.json
          git commit -m "Update stock.json" || exit 0
          git push
