name: Check Stock

on:
  schedule:
    - cron: '0 */2 * * *' # Draait bijvoorbeeld elke 2 uur
  workflow_dispatch: # Zorgt ervoor dat je de check ook handmatig kunt starten

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run all checkers
        run: |
          python -c "import glob, os; [os.system(f'python {f}') for f in glob.glob('check_*.py')]"

      - name: Commit and push stock.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stock.json
          git commit -m "Update stock.json" || exit 0
          git push
